spring:
  datasource:
    url: jdbc:mysql://trainticketbookingdb.c3y8qcq6w20x.us-east-1.rds.amazonaws.com:3306/trainticketbooking?createDatabaseIfNotExist=true
    username: admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
